### ISSUE TITLE
Incompatible mix of packages  

### ISSUE THREAD

**Issue by maxwell-k** [CypherpunkArmory/UserLAnd-Assets-Alpine#10]
The current setup for Alpine Linux mixes incompatible packages from
latest-stable and edge.

Edge for Alpine Linux is an unsupported rolling build of packages, see [what is
edge], whereas latest-stable is a supported release.

The UserLAnd scripts at present install packages from the main repository from
latest-stable and from the community repository from edge. These packages are
not compatible.

For example at present:

- the latest stable release is 3.9.3, see [Downloads]
- 3.9.3 [uses Python 3.6]
- edge currently [uses Python 3.7]

<details>

```
localhost:~$ cat /etc/apk/repositories
http://dl-5.alpinelinux.org/alpine/latest-stable/main
http://dl-cdn.alpinelinux.org/alpine/edge/community
localhost:~$ sudo apk add youtube-dl
fetch http://dl-5.alpinelinux.org/alpine/latest-stable/main/x86/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86/APKINDEX.tar.gz
(1/5) Installing gdbm (1.13-r1)
(2/5) Installing xz-libs (5.2.4-r0)
(3/5) Installing sqlite-libs (3.26.0-r3)
(4/5) Installing python3 (3.6.8-r2)
(5/5) Installing youtube-dl (2019.04.30-r0)
Executing busybox-1.29.3-r10.trigger
ERROR: busybox-1.29.3-r10.trigger: script exited with error 127
OK: 303 MiB in 145 packages
localhost:~$ youtube-dl --version
Traceback (most recent call last):
  File "/usr/bin/youtube-dl", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3126, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3110, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3139, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 784, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'youtube-dl==2019.4.30' distribution was not found and is required by the application
localhost:~$
```

</details>

Packages from the two repositories below are incompatible:

- Main repository: latest-stable (released)
- Community repository: edge (unreleased)

[what is edge]: https://wiki.alpinelinux.org/wiki/Aports_what_is_edge
[downloads]: https://www.alpinelinux.org/downloads/
[uses python 3.6]: https://pkgs.alpinelinux.org/package/v3.9/main/x86/python3
[uses python 3.7]: https://pkgs.alpinelinux.org/package/edge/main/x86/python3

**Comment by carbonatedcaffeine** [comment]
Thanks for that issue. I don't know how alpine works... Thanks for the pull, I think it will help a lot.

**Comment by corbinlc** [comment]
This has been pushed out to the world now.
