### ISSUE TITLE
Please rebuild the Alpine image (Alpine Linux 3.9.4 released)

### ISSUE THREAD

**Issue by maxwell-k** [CypherpunkArmory/UserLAnd-Assets-Alpine#13]
First thank you for this project. I know I'm not paying for it. I appreciate your work.

Yesterday, 9 May 2019, Alpine Linux released 3.9.4 including a number of security fixes. 
<https://alpinelinux.org/posts/Alpine-3.9.4-released.html>

Would it be possible to get a fresh image built please? This would also incorporate the fixes from:
<https://github.com/CypherpunkArmory/UserLAnd-Assets-Alpine/pull/11>

Thanks again for your work on UserLAnd!

**Comment by carbonatedcaffeine** [comment]
I will try to do it in my spare time... I'm very busy at school and tests. And corbin says he has been very busy lately... I will try to get on it as soon as I can. Thanks.

**Comment by corbinlc** [comment]
I just pushed out a version based on the latest alpine docker image, which is 3.9.4.  Just grabbing the latest dockerhub image also greatly simplifies how we create images...as opposed to us bootstrapping it ourselves.
